# Generated by Django 5.1.1 on 2024-10-07 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
